[project]
authors = ["Manuel Saelices <msaelices@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Library for dealing with regular expressions in Mojo"
name = "mojo-regex"
platforms = ["linux-64", "osx-arm64"]
version = "0.4.0"

[dependencies]
max = ">=25.4.0.dev2025053005"
