[project]
authors = ["Manuel Saelices <msaelices@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Library for dealing with regular expressions in Mojo"
name = "mojo-regex"
platforms = ["linux-64", "osx-arm64"]
version = "0.4.0"

[dependencies]
max = ">=25.4.0.dev2025053005"

[tasks]
test = "mojo test -I ./src tests/"
format = "mojo format"
template = "python tools/mojopkg.py generate-recipe"
build = { cmd = "python tools/mojopkg.py build-conda-package" }
publish = { cmd = "python tools/mojopkg.py publish", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" } }
build-and-publish = { cmd = "python tools/mojopkg.py build-and-publish" }
