[workspace]
authors = ["Manuel Saelices <msaelices@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Library for dealing with regular expressions in Mojo"
homepage = "https://github.com/msaelices/mojo-regex"
repository = "https://github.com/msaelices/mojo-regex"
license = "MIT"
license-file = "LICENSE"
name = "mojo-regex"
platforms = ["linux-64", "osx-arm64"]
preview = ["pixi-build"]
version = "0.4.0"

[package]
name = "mojo-regex"
version = "0.2.1"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[dependencies]
max = ">=25.4.0"

[tasks]
test = "mojo test -I ./src tests/"
format = "mojo format benchmarks/ src/regex/ tests/"

[feature.mojopkg.dependencies]
pyyaml = ">=6.0.2,<7"

[environments]
default = { solve-group = "default" }
mojopkg = { features = ["mojopkg"], solve-group = "default" }
