name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.42.0

    - name: Install pre-commit hooks
      run: pixi x pre-commit install

    - name: Run pre-commit checks
      run: pixi x pre-commit run --all-files
    - name: Run tests
      run: pixi run test
